(function(g){var window=this;var A3=function(a){var b={languageCode:a.languageCode,languageName:a.languageName,displayName:g.Zz(a),kind:a.kind,name:a.name,id:a.id,is_servable:a.o,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.vssId};a.translationLanguage&&(b.translationLanguage=a.translationLanguage);return b},B3=function(a){return a.translationLanguage?a.translationLanguage.languageCode:a.languageCode},Zwa=function(a,b){var c=new g.Yz;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.o=a.o;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},$wa=function(){this.u=[];
this.o=[]},C3=function(a,b){switch(b.kind){case "asr":axa(b,a.u);
break;default:axa(b,a.o)}},axa=function(a,b){g.db(b,function(c){return c?a.toString()===c.toString():!1})||b.push(a)},D3=function(){g.B.call(this);
this.u=new $wa;this.B=[]},E3=function(a,b,c){D3.call(this,a);
this.audioTrack=c;this.o=null;this.B=b.ty},F3=function(){this.segments=[]},bxa=function(a,b){var c=g.vb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.kb(a.segments,c),g.kb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.sb(a.segments,c,0,b),g.sb(a.segments,c+1,0,b)))},G3=function(a,b,c,d,e,f){g.B.call(this);
this.policy=a;this.player=b;this.N=c;this.F=d;this.C=e;this.I=f;this.M=this.player.O();this.B=new F3;this.u=this.A=this.o=null;this.G=new g.H(this.zA,1E3,this);this.events=new g.ds(this);g.C(this,this.G);g.C(this,this.events);this.events.L(b,"SEEK_COMPLETE",this.BC);this.BC();this.zA()},cxa=function(a,b){var c=g.Gv(b,a.policy,{}).yc(),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.u=g.Gr(c,d,3,100).then(function(e){a.ia();var f=!(a.C?e.response:e.responseText)||400<=e.status,h=g.uw(e);h?(e=g.Gv(a.A,a.policy,{}),f=a.A,g.Cv(f.u,e,h),f.requestId=e.get("req_id"),cxa(a,a.A)):(f||null==a.F||(h=a.A.o[0],a.C?a.F(e.response,1E3*(h.startTime+a.player.Ib())):a.F(e.responseText,1E3*(h.startTime+a.player.Ib()))),a.A=null,a.u=null)});
a.A=b;bxa(a.B,a.A.o[0].u)},H3=function(a,b){D3.call(this,b.O());
this.ka=a;this.H=b;this.o=null;this.A=!1;this.C=g.Sy(this.H.O())&&!this.ka.u},dxa=function(a,b){var c=[],d;
for(d in a.ka.o)if(a.ka.o.hasOwnProperty(d)){var e=a.ka.o[d];if(g.SN(e,b||null)){var f="en",h="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;c.push(new g.Yz({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},exa=function(a,b){return null!=b&&b in a.ka.o?a.ka.o[b]:null},fxa=function(a,b,c){var d=[],e;
for(e in a.ka.o)if(a.ka.o.hasOwnProperty(e)){var f=a.ka.o[e];if(g.SN(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},I3=function(a,b,c,d,e){D3.call(this,e||null);
this.videoId=b;this.cA=d;this.C={};this.o=null;b=c||g.dq(a).hl||"";b=b.split("_").join("-");this.A=g.fq(a,{hl:b})},J3=function(a,b,c,d,e,f,h){var l={};
g.Ua(l,b);g.Ua(l,a.params);g.Ua(l,c);var m={};g.Ua(m,b.Jb);a.params.Jb&&g.Ua(m,a.params.Jb);g.Ua(m,c.Jb);l.Jb=m;g.U.call(this,{D:"div",J:"caption-window",P:{id:"caption-window-"+a.id,dir:1===l.o?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:l.lang},K:[{D:"span",J:"captions-text",P:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.T=!1;this.u=a;this.Z=this.U=null;this.playerWidth=e;this.playerHeight=f;this.experiments=h;this.F=null;this.maxWidth=.96*e;this.wa=.96*f;this.o=l;this.Fa=
c;this.B=this.da("captions-text");this.Aa=""!==this.B.style.getPropertyValue("box-decoration-break")||""!==this.B.style.getPropertyValue("-webkit-box-decoration-break");this.aa=d/360*16;this.type=0;this.ga=this.aa*gxa(m);a=new g.js(this.element,!0);g.C(this,a);a.subscribe("dragstart",this.jJ,this);a.subscribe("dragmove",this.iJ,this);a.subscribe("dragend",this.hJ,this);this.ua=this.oa=0;b="";this.o.windowOpacity&&(a=g.y1(this.o.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.o.windowOpacity+
")");a={"background-color":b,display:!1===this.o.isVisible?"none":"","text-align":hxa[this.o.textAlign]};this.Aa&&(a["border-radius"]=b?this.ga/8+"px":"");if(this.A=2===this.u.params.o||3===this.u.params.o)b=this.element,c="vertical-rl",1===this.o.A&&(c="vertical-lr"),g.pe&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.Bh(b,"-o-writing-mode",c),g.Bh(b,"-webkit-writing-mode",c),g.Bh(b,"writing-mode",c),g.Bh(b,"text-orientation","upright"),g.I(b,"ytp-vertical-caption"),3===this.u.params.o&&(g.Bh(b,"text-orientation",
""),g.Bh(b,"transform","rotate(180deg)"));g.Bh(this.element,a);switch(this.o.vf){case 0:case 1:case 2:g.I(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.I(this.element,"ytp-caption-window-bottom")}},gxa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},ixa=function(a,b){var c={},d=b.background?b.background:a.o.Jb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.o.Jb.backgroundOpacity;d=g.y1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Aa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ga/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.aa*gxa(b)+"px";d=1;e=b.color||a.o.Jb.color;if(b.color||null!=b.textOpacity)e=g.y1(e),d=null==b.textOpacity?a.o.Jb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.vt&&(h=e=b.vt);var l=a.aa/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=r;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.kl()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.o.Jb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Lf&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.xH&&(c.visibility="hidden");1===b.Zz&&a.A&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.Wy||g.Xy,3===a.u.params.o?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.dg||2===b.dg||3===b.dg||4===b.dg||5===b.dg)if(g.Wy)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.dg){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},jxa=function(a){a.F=g.we("SPAN");
g.Bh(a.F,{display:"block"});g.I(a.F,"caption-visual-line");a.B.appendChild(a.F)},kxa=function(a,b){var c=g.we("SPAN");
g.Bh(c,{display:"inline-block","white-space":"pre-wrap"});g.Bh(c,ixa(a,b));c.classList.add("ytp-caption-segment");a.F.appendChild(c);c.previousElementSibling&&(g.Bh(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Bh(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},lxa=function(a,b,c){a.T=a.T||!!c;
var d={};g.Ua(d,a.o.Jb);g.Ua(d,c||b.o);g.Ua(d,a.Fa.Jb);(c=!a.F)&&jxa(a);for(var e=a.U&&a.Z&&g.Qb(d,a.Z)?a.U:kxa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(jxa(a),e=kxa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.xe(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.Wy||!g.Fh(n.children[2],"text-emphasis")||(m=a.A?"padding-right":"padding-top",g.Fh(n.children[2],"text-emphasis-position")&&(m=a.A?"padding-left":"padding-bottom"),
g.re?g.Bh(e,m,"1em"):g.Bh(e,m,"0.5em")))}a.Z=d;a.U=e;a.C.push(b)},K3=function(a,b,c,d,e,f,h){J3.call(this,a,b,c,d,e,f,h);
this.type=1},L3=function(a,b,c,d,e,f,h){J3.call(this,a,b,c,d,e,f,h);
this.type=2;this.G=[];this.N=this.I=this.ba=0;this.R=NaN;this.za=0;this.Ea=null;this.fa=new g.H(this.nN,433,this);g.I(this.element,"ytp-caption-window-rollup");g.C(this,this.fa);g.Bh(this.element,"overflow","hidden")},mxa=function(a,b){return(a.A?b.offsetHeight:b.offsetWidth)+1},nxa=function(a){if(isNaN(a.R)){var b=a.o.ai;
if(b){var c=g.we("SPAN");g.Fe(c,"\u2013".repeat(b));g.Bh(c,ixa(a,a.o.Jb));a.B.appendChild(c);a.R=c.offsetWidth;a.B.removeChild(c)}else a.R=0}return a.R},oxa=function(a,b){if(!b)return"";
a.A&&1!==a.u.params.A&&(b*=-1);return"translate"+(a.A?"X":"Y")+"("+b+"px)"},pxa=function(a){a.G=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.u,c=0,d=0,e=a.G.length-1;c<b&&-1<e;){var f=a.G[e];d+=a.A?f.offsetWidth:f.offsetHeight;c++;e--}a.G.length<b&&(d*=b/a.G.length);a.I=d;a.N=Math.max(nxa(a),a.za,mxa(a,a.B))},qxa=function(a,b){pxa(a);
var c=a.G.reduce(function(e,f){return(a.A?f.offsetWidth:f.offsetHeight)+e},0);
c=a.I-c;if(c!==a.ba){var d=0<c&&0===a.ba;b||isNaN(c)||d||(g.I(a.element,"ytp-rollup-mode"),a.fa.ib());g.Bh(a.B,"transform",oxa(a,c));a.ba=c}pxa(a)},M3=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.ez.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.o=h},N3=function(a,b,c,d,e){g.ez.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},rxa=function(a){var b="_"+O3++;
return new N3(0,0x8000000000000,0,b,a)},txa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.oc){var n=f[1],q=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");q.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[q.getAttribute("p")];l=sxa(l.textContent,n.textContent,q.textContent,f.textContent,h);return new M3(a,b,e,c,l,d,m)}switch(m.oc){case 9:case 10:m.dg=1;break;case 11:m.dg=2;break;case 12:m.dg=3;break;case 13:m.dg=4;break;case 14:m.dg=5}return new M3(a,b,e,c,l.textContent||"",d,m)},sxa=function(a,b,c,d,e){var f=g.kl(),h=
f?g.we("DIV"):g.we("RUBY"),l=g.we("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.we("DIV"):g.we("RP");a.textContent=b;h.appendChild(a);b=f?g.we("DIV"):g.we("RT");b.textContent=c;h.appendChild(b);c=e.oc;if(10===c||11===c||12===c||13===c||14===c)if(g.Bh(b,"text-emphasis-style","filled circle"),g.Bh(b,"text-emphasis-color","currentcolor"),g.Bh(b,"webkit-text-emphasis","filled circle"),11===e.oc||13===e.oc)g.Bh(b,"webkit-text-emphasis-position","under left"),g.Bh(b,"text-emphasis-position","under left");c=!0;if(4===e.oc||7===e.oc||12===e.oc||
14===e.oc)g.Bh(h,"ruby-position","over"),g.Bh(h,"-webkit-ruby-position","before");else if(5===e.oc||6===e.oc||11===e.oc||13===e.oc)g.Bh(h,"ruby-position","under"),g.Bh(h,"-webkit-ruby-position","after"),c=!1;e=f?g.we("DIV"):g.we("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.Bh(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.Bh(f,"display","none"),f=f.nextElementSibling,g.Bh(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Bh(h.lastElementChild,"display","none"),d?(g.Bh(h,"padding-top","0.6em"),g.Bh(f,"top","0")):(g.Bh(h,"padding-bottom","0.6em"),g.Bh(f,"bottom","0")));return h},P3=function(){g.B.apply(this,arguments)},Q3=function(a){P3.call(this);
this.F=a;this.B={};this.M={};this.N={};this.C="_"+O3++;this.I={};this.u=this.o=null;this.G=!0},R3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Number(c)},S3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"===c},T3=function(a,b){var c=R3(a,b);
return void 0!==c?c:null},V3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return U3.test(c),c},uxa=function(a,b){var c={},d=b.getAttribute("ws");
g.Ua(c,d?a.N[d]:a.F);d=T3(b,"mh");null!=d&&(c.vl=d);d=T3(b,"ju");null!=d&&(c.textAlign=d);d=T3(b,"pd");null!=d&&(c.o=d);d=T3(b,"sd");null!=d&&(c.A=d);d=V3(b,"wfc");null!=d&&(c.windowColor=d);d=R3(b,"wfo");void 0!==d&&(c.windowOpacity=d/255);return c},vxa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ua(c,a.M[d]);d=T3(b,"ap");null!=d&&(c.vf=d);d=R3(b,"cc");null!=d&&(c.ai=d);d=R3(b,"ah");null!=d&&(c.Ne=d);d=R3(b,"rc");null!=d&&(c.u=d);d=R3(b,"av");null!=d&&(c.gg=d);return c},wxa=function(a,b,c,d){var e={};
g.Ua(e,vxa(a,b));g.Ua(e,uxa(a,b));d?g.Qb(e,a.F)?(d=a.C,e=a.F):d="_"+O3++:d=b.getAttribute("id")||"_"+O3++;a=R3(b,"t")+c;b=R3(b,"d")||0x8000000000000;if(2===e.o||3===e.o)c=e.u,e.u=e.ai,e.ai=c;return new N3(a,b,0,d,e)},W3=function(a){P3.call(this);
this.F=a;this.o=new Map;this.B=new Map;this.C=new Map;this.u=new Map},X3=function(a){a=g.Vd(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},xxa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.B.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.C.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.u=a);b=b.ccColCount;void 0!==b&&(f.ai=b);if(2===f.o||3===f.o)b=f.u,f.u=f.ai,f.ai=b;return new N3(c,d,0,e,f)},Z3=function(){this.A=this.time=this.mode=this.u=0;
this.B=new Y3(this);this.C=new Y3(this);this.o=[];this.clear()},zxa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{lj:a,
Xh:b,result:0};a=yxa[a];b=yxa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Xh===d;if(d)return{lj:a,Xh:b,result:1}}else if(b&128&&1<=a&&31>=a)return{lj:a,Xh:b,result:2};return{lj:a,Xh:b,result:3}},Bxa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.A&&a.reset(),a.B.o.clear(),a.C.o.clear()):(a.A=0,Axa(a.B,b,c,d))},Cxa=function(a,b){a.o.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.p(a.o),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?Bxa(a,d.vy,d.wy,b):1===d.type&&a.u&496&&Axa(a.C,d.vy,d.wy,b);a.o.length=0},$3=function(){this.type=0},a4=function(){this.state=this.Xh=this.lj=0},Dxa=function(){this.timestamp=this.o=0},b4=function(a){this.C=a;
this.A=[];this.o=this.u=this.row=0;this.style=new $3;for(a=this.B=0;15>=a;a++){this.A[a]=[];for(var b=0;32>=b;b++)this.A[a][b]=new Dxa}},c4=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.C.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.A[m][q];
if(0!==r.o){0===c&&(c=m,d=q);n=String.fromCharCode(r.o);var u=r.timestamp;u<e&&(e=u);r.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===r.o||32===q)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.C.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(q=a.A[h][m],r=q.o,0!==r&&(0===c&&(c=h,d=m),n=String.fromCharCode(r),u=q.timestamp,u<=e&&(e=u),l+=n,q.reset()),32===m||0===r)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},Ixa=function(a,b){switch(a){case 0:return Exa[(b&127)-32];
case 1:return Fxa[b&15];case 2:return Gxa[b&31];case 3:return Hxa[b&31]}return 0},d4=function(a){return a.A[a.row][a.u]},e4=function(a,b,c){2<=b&&1<a.u&&(--a.u,d4(a).o=0);
var d=d4(a);d.timestamp=a.C.time+0;d.o=Ixa(b,c);32>a.u&&a.u++},Jxa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.A[b+e][f],l=a.A[c+e][f];
h.o=l.o;h.timestamp=l.timestamp}},f4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.A[b+d][e].reset()},g4=function(a){a.row=0<a.o?a.o:1;
a.u=1;f4(a,0,15)},h4=function(a){this.A=a;
this.C=0;this.style=new $3;this.F=new b4(this.A);this.G=new b4(this.A);this.text=new b4(this.A);this.u=this.F;this.B=this.G;this.o=this.u},i4=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.o||(c4(d,c),g4(a.u),g4(a.B),d.row=15,d.o=b,e=!0)}a.style.set(3);a.o=d;a.o.style=a.style;a.A.mode=1<<d.B;e?d.u=1:d.o!==b&&(d.o>b?(c4(d,c),f4(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},Kxa=function(a){a.style.set(1);
a.o=a.B;a.o.o=0;a.o.style=a.style;a.A.mode=1<<a.o.B},Lxa=function(a){a.style.set(4);
a.o=a.text;a.o.style=a.style;a.A.mode=1<<a.o.B},Y3=function(a){this.u=a;
this.C=0;this.A=new h4(this.u);this.F=new h4(this.u);this.o=new a4;this.B=this.A},Axa=function(a,b,c,d){a.o.update();
b=zxa(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.lj;c=b.Xh;if(32<=e||!e)a.u.mode&a.u.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.B.o,b&96&&e4(a,0,b),c&96&&e4(a,0,c),0!==b&&0!==c&&3===a.style.type&&c4(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.lj=e,b.Xh=c,b.state=2,b=e&8?a.F:a.A,a.B=b,a.u.mode=1<<(a.C<<2)+(b.C<<1)+(4===b.style.type?1:0),(a.u.mode|1<<(a.C<<2)+(b.C<<1)+(4!==b.style.type?1:0))&a.u.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.o&&(d=c.o,d===c.row))break;var f=1+c.row-c.o,h=1+d-c.o;Jxa(c,h,f,c.o);b=f;e=c.o;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));f4(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:e4(b.o,0,32);break a;case 48:57===c?(d=b.o,d4(d).o=0,32>d.u&&d.u++):e4(b.o,1,c&15)}break;case 2:c&32&&e4(b.o,2,c&31);break;case 3:c&32&&e4(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:Kxa(b);
break;case 33:d=b.o;1<d.u&&(--d.u,d4(d).o=0);break;case 36:d=b.o;b=d4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.A[a][c]===b){for(;32>=c;c++)d.A[a][c].reset();break}break;case 37:i4(b,2,d);break;case 38:i4(b,3,d);break;case 39:i4(b,4,d);break;case 40:e4(b.o,0,32);break;case 41:b.style.set(2);b.o=b.u;b.o.o=0;b.o.style=b.style;b.A.mode=1<<b.o.B;break;case 42:d=b.text;d.o=15;d.style.set(4);g4(d);Lxa(b);break;case 43:Lxa(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:c4(a,d)}f4(a,
0,15);break;case 45:b:{a=b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;c4(a,d);Jxa(a,b,b+1,a.o-1);f4(a,a.row,1)}break;case 46:f4(b.B,0,15);break;case 47:c4(b.u,d),b.B.updateTime(b.A.time+0),d=b.B,b.B=b.u,b.u=d,Kxa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.o,32<(d.u+=c&3)&&(d.u=32)}}},Mxa=function(){},j4=function(a,b,c){this.I=a;
this.G=c;this.version=this.F=this.B=this.o=0;this.u=new DataView(this.I);this.A=[]},k4=function(a){var b=a.o;
a.o+=1;return a.u.getUint8(b)},l4=function(a){var b=a.o;
a.o+=4;return a.u.getUint32(b)},m4=function(a,b){P3.call(this);
this.u=a;this.B=b;this.track="CC3"===this.B.languageName?4:0;this.o=new Z3;this.o.u=1<<this.track},n4=function(a){if("string"===typeof a)return!1;
a=new j4(a,8,0);return Nxa(a)},Nxa=function(a){if(!(a.o<a.u.byteLength)||1380139777!==l4(a))return!1;
a.version=k4(a);if(1<a.version)return!1;k4(a);k4(a);k4(a);return!0},o4=function(){P3.call(this)},Oxa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.Lf=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var q=h.childNodes[n];if(3===q.nodeType)q=new M3(b,c,d,e.id,q.nodeValue,f||0<n,g.Ob(l)?void 0:l),m.push(q),e.o.push(q);else{var r={};g.Ua(r,l);Oxa(a,b,c,d,e,!0,q,r,m)}}},p4=function(a){var b=a.split(":");
a=0;b=g.p(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},Pxa=function(a,b,c,d){d=Object.assign({vl:0},d);
return new N3(a,b,c,"_"+O3++,d)},q4=function(a){g.B.call(this);
this.u=a;this.o=null},Rxa=function(a){var b={};
if(a=B3(a))b.lang=a,Qxa.test(a)&&(b.o=1);return b},t4=function(a){g.RN.call(this,a);
this.H=a;this.A=this.H.O();this.videoData=this.H.getVideoData();this.wa=g.mN(this.H);this.B={Jb:{}};this.F={Jb:{}};this.R=[];this.M={};this.ea={};this.U=!1;this.oa=g.TN(this.videoData,this.H);this.za=!!this.videoData.captionTracks.length;this.Aa=!!this.videoData.qm;this.ga="3"===this.A.controlsType;this.u=this.G=this.I=this.ba=this.sa=null;this.fa=new q4(this.A);this.o=null;this.Z=new g.ds(this);var b=null,c=g.oo("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.bo(c));this.storage=b;b=
a.app.C;c=!(!b||!b.no());this.ua=!(!b||!b.zk());this.C=this.ga&&c&&!this.oa;this.N=!this.C&&this.ga&&this.ua&&this.oa;g.C(this,this.fa);this.C?this.aa=this.T=null:(this.T=new g.zn(this.lE,void 0,this),g.C(this,this.T),this.aa=new g.H(this.GO,2E3,this),g.C(this,this.aa));g.C(this,this.Z);this.C||this.Z.L(a,"resize",this.ax);this.Z.L(a,"onPlaybackAudioChange",this.dL);this.Z.L(a,g.hz("captions"),this.kJ,this);this.Z.L(a,"crx_captions",this.lJ,this);r4(this,s4(this,"display-settings")||{})},u4=function(a){if(1===
a.A.Zh||1===a.videoData.Zh||"alwayson"===g.PB(a.videoData,"yt:cc"))return!0;
if(2===a.A.Zh){var b=s4(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().nt;return"ON"===c||"on"===g.PB(a.videoData,"yt:cc")},v4=function(a,b){if(a.o&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.Ep||"FORCED_ON"===c.nt},x4=function(a,b){if(a.u){if(a.G&&a.G.o)return a.G.o;
var c=b;c||(c=a.Aa?!1:a.za?!1:!0);c=a.u.Ej(c);for(var d=[a.videoData.captionsLanguagePreference,a.A.captionsLanguagePreference,g.PB(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(B3(c[f])===d[e])return c[f];return a.G&&a.G.Ht?a.G.Ht:(d=c.find(function(h){return h.isDefault}))?d:c[0]||w4(a)}return null},w4=function(a){return a.G&&a.G.Ep},y4=function(a){var b=w4(a);
return!!b&&a.o===b},Sxa=function(a,b){for(var c=a.H.app.C.xa().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id===d&&(b?"showing"!==f.mode&&(f.mode="showing"):"showing"===f.mode&&(f.mode="disabled"))}},A4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.U=c,a.U&&z4(a,"module-enabled",!!b));a.o=b;v4(a)&&(a.o=w4(a));a.load()},Txa=function(a,b){var c=a.wa.getVideoContentRect(!0).height;
if(!c)return null;var d=a.o?a.o.languageCode:null;!b.params.o&&d&&Qxa.test(d)&&(b.params.o=1);d=a.wa.getPlayerSize();switch(null!=b.params.vl?b.params.vl:1<b.o.length?1:0){case 1:return new K3(b,a.B,a.F,c,d.width,d.height,a.A.experiments);case 2:return new L3(b,a.B,a.F,c,d.width,d.height,a.A.experiments);default:return new J3(b,a.B,a.F,c,d.width,d.height,a.A.experiments)}},r4=function(a,b,c){c=void 0===c?!1:c;
var d=B4.Jb;a.B={};g.Ua(a.B,B4);a.B.Jb={};g.Ua(a.B.Jb,d);a.F={Jb:{}};var e=b.backgroundOverride?a.F:a.B,f=b.background||d.background;U3.test(f);e.Jb.background=f;e=b.colorOverride?a.F:a.B;f=b.color||d.color;U3.test(f);e.Jb.color=f;e=b.windowColorOverride?a.F:a.B;f=b.windowColor||B4.windowColor;U3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.F:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Jb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.F:a.B;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.Jb.fontSizeIncrement=f;f=b.fontStyleOverride?a.F:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.Lf?3:d.bold?1:d.Lf?2:0);f=f.Jb;switch(e){case 1:f.bold=!0;delete f.Lf;break;case 2:delete f.bold;f.Lf=!0;break;case 3:f.bold=!0;f.Lf=!0;break;default:delete f.bold,delete f.Lf}e=b.textOpacityOverride?a.F:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Jb.textOpacity=f;e=b.windowOpacityOverride?a.F:a.B;f=b.windowOpacity;null==f&&(f=B4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.F:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Jb.charEdgeStyle=f;e=b.fontFamilyOverride?a.F:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Jb.fontFamily=f;a.loaded&&a.ax();c&&z4(a,"display-settings",b)},Vxa=function(a,b){if(b&&!a.I){var c=rxa({o:0,
lang:"en"});a.I=[c,new M3(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.zN(a.player,a.I)}else!b&&a.I&&(Uxa(a,a.I),a.I=null)},Uxa=function(a,b){g.zU(a.player.app,b,void 0);
(0,g.y)(b,function(c){g.lb(this.R,c)},a);
a.T.ib()},s4=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},z4=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}};
g.zC.prototype.sm=g.da(11,function(){for(var a=g.ie(document,"track",void 0,this.o),b=0;b<a.length;b++)g.Be(a[b])});
g.DC.prototype.sm=g.da(10,function(){this.o.sm()});
g.zC.prototype.no=g.da(9,function(){return!!this.o.textTracks});
g.DC.prototype.no=g.da(8,function(){return this.o.no()});
g.zC.prototype.lm=g.da(7,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.DC.prototype.lm=g.da(6,function(a){this.o.lm(a)});
g.qC.prototype.zk=g.da(5,function(){});
g.zC.prototype.zk=g.da(4,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.DC.prototype.zk=g.da(3,function(){return this.o.zk()});
g.it.prototype.Tp=g.da(1,function(a){return(a=this.qg(a))?a.o:0});
g.mw.prototype.Tp=g.da(0,function(){return 0});
var Qxa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;$wa.prototype.Ej=function(a){return a?this.o.concat(this.u):this.o};
g.t(D3,g.B);g.k=D3.prototype;g.k.Ej=function(a){return this.u.Ej(a)};
g.k.yq=function(){};
g.k.zq=function(){};
g.k.Nh=function(){};
g.k.Yk=function(){return""};
g.k.XC=function(){return!1};
g.k.X=function(){this.Nh();g.B.prototype.X.call(this)};
g.t(E3,D3);E3.prototype.yq=function(a,b,c){var d=this;this.ia();b=this.Yk(a,b);this.Nh();this.o=g.vq(b,{format:"RAW",onSuccess:function(e){d.o=null;c(e.responseText,a)},
withCredentials:!0})};
E3.prototype.zq=function(a){if(this.audioTrack)for(var b=g.p(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())C3(this.u,c.value);a()};
E3.prototype.Yk=function(a,b){var c=a.yc(),d={fmt:b};if("srv3"===b||"3"===b||"json3"===b)g.kl()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.translationLanguage&&(d.tlang=B3(a));return g.fq(c,d)};
E3.prototype.Nh=function(){this.o&&this.o.abort()};
F3.prototype.contains=function(a){a=g.vb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
F3.prototype.length=function(){return this.segments.length/2};
g.t(G3,g.B);g.k=G3.prototype;g.k.X=function(){g.B.prototype.X.call(this);this.u&&this.u.cancel()};
g.k.BC=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Ib();var b=this.o;this.o=g.bb(this.N.oh(a).o);b!==this.o&&this.I&&this.I()};
g.k.reset=function(){this.B=new F3;this.u&&(this.u.cancel(),this.u=null)};
g.k.zA=function(){this.ia();var a;if(a=null!=this.o)a=this.o,a=a.o.Fh(a);!a||this.u||this.o&&30<this.o.startTime-this.player.getCurrentTime()||(a=this.o.ji(),a.o[0].duration?(this.B.contains(a.o[0].u)||cxa(this,a),this.o=g.bb(a.o)):!g.P(this.M.experiments,"force_caption_seek_for_live_killswitch")&&this.o&&this.o.F&&this.o.F+this.player.Ib()<this.player.getCurrentTime()&&this.seekTo(this.player.getCurrentTime()));this.G.start()};
g.t(H3,D3);g.k=H3.prototype;g.k.yq=function(a,b,c){var d=this;this.Nh();b=exa(this,a.getId());b||(b=a.languageCode,b=this.ka.u?fxa(this,b,"386"):fxa(this,b));if(b){var e=1E3*(b.index.Tp(b.index.Gf())-b.index.xd(b.index.Gf()));this.o=new G3(new g.Zu,this.H,b,function(f,h){c(f,a,h,e)},this.C||g.Pu(b.info),function(){d.o&&d.o.reset();
d.A=!0})}};
g.k.XC=function(){var a=this.A;this.A=!1;return a};
g.k.zq=function(a){var b;this.C?b=[new g.Yz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Yz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.ka.u?dxa(this,"386"):dxa(this);b=g.p(b);for(var c=b.next();!c.done;c=b.next())C3(this.u,c.value);a()};
g.k.Nh=function(){this.o&&(this.o.dispose(),this.o=null)};
g.k.Yk=function(){return""};
g.t(I3,D3);I3.prototype.yq=function(a,b,c){var d=this;this.ia();b=this.Yk(a,b);this.Nh();this.o=g.vq(b,{format:"RAW",onSuccess:function(e){d.o=null;c(e.responseText,a)},
withCredentials:!0})};
I3.prototype.zq=function(a){var b=this,c=this.A,d={type:"list",tlangs:1,v:this.videoId,vssids:1};this.cA&&(d.asrs=1);c=g.fq(c,d);this.Nh();this.o=g.vq(c,{format:"RAW",onSuccess:function(e){b.o=null;if((e=e.responseXML)&&e.firstChild){for(var f=e.getElementsByTagName("track"),h=0;h<f.length;h++){var l=f[h],m=l.getAttribute("lang_code"),n=l.getAttribute("lang_translated"),q=l.getAttribute("name"),r=l.getAttribute("kind"),u=l.getAttribute("id"),w="true"===l.getAttribute("lang_default"),z="true"===l.getAttribute("cantran");
l=l.getAttribute("vss_id");C3(b.u,new g.Yz({languageCode:m,languageName:n,name:q,kind:r,id:u,is_servable:!0,is_translateable:z,vss_id:l,is_default:w}))}e=e.getElementsByTagName("target");f=e.length;for(h=0;h<f;h++)m={languageCode:e[h].getAttribute("lang_code"),languageName:e[h].getAttribute("lang_translated"),languageOriginal:e[h].getAttribute("lang_original"),id:e[h].getAttribute("id"),isDefault:"true"===e[h].getAttribute("lang_default")},b.C[m.languageCode]=m.languageName,b.B.push(m)}a()},
withCredentials:!0})};
I3.prototype.Yk=function(a,b){var c=this.A,d={v:this.videoId,type:"track",lang:a.languageCode,name:a.getName(),kind:a.kind,fmt:b};a.translationLanguage&&(d.tlang=B3(a));return c=g.fq(c,d)};
I3.prototype.Nh=function(){this.o&&this.o.abort()};
var U3=/^#(?:[0-9a-f]{3}){1,2}$/i;var hxa=["left","right","center","justify"];g.t(J3,g.U);g.k=J3.prototype;g.k.jJ=function(a,b){var c=g.Rh(this.element,this.element.parentElement);this.oa=a-c.x;this.ua=b-c.y;g.I(this.element,"ytp-dragging")};
g.k.iJ=function(a,b){var c=g.Uh(this.element),d=a-this.oa-.02*this.playerWidth,e=b-this.ua-.02*this.playerHeight,f=(d+c.width/2)/this.maxWidth*3;f=Math.floor(g.Vd(f,0,2));var h=(e+c.height/2)/this.wa*3;h=Math.floor(g.Vd(h,0,2));var l=f+3*h;d=(d+f/2*c.width)/this.maxWidth;d=100*g.Vd(d,0,1);c=(e+h/2*c.height)/this.wa;c=100*g.Vd(c,0,1);this.u.params.vf=l;this.u.params.gg=c;this.u.params.Ne=d;this.o.vf=l;this.o.gg=c;this.o.Ne=d;this.AD()};
g.k.hJ=function(){g.In(this.element,"ytp-dragging")};
g.k.AD=function(){this.wk(this.C)};
g.k.wk=function(a){var b=Math.min(this.sz(),this.maxWidth),c=this.rz(),d="";3===this.u.params.o&&(d="rotate(180deg)");g.Bh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.gt(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.o.Ne+2;d=this.o.vf;switch(d){case 0:case 3:case 6:b=this.o.Jb.fontSizeIncrement;!g.P(this.experiments,"web_player_ignore_left_percentage_for_large_font_killswitch")&&
b&&2<b&&2!==this.o.o&&3!==this.o.o&&(e=2);a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.B.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.o.gg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-
b+"%"}g.Bh(this.element,a)};
g.k.gt=function(a){var b;for(b=0;b<a.length&&a[b]===this.C[b];b++);if(this.T||this.C.length>b)b=0,this.T=!1,this.C=[],this.F=this.Z=this.U=null,g.ze(this.B);for(;b<a.length;b++)lxa(this,a[b])};
g.k.sz=function(){return 0};
g.k.rz=function(){return 0};
g.k.toString=function(){return g.U.prototype.toString.call(this)};g.t(K3,J3);K3.prototype.gt=function(a){var b=this.u.o;J3.prototype.gt.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o===e)var d=f;else{d={};g.Ua(d,c.o);g.Ua(d,Wxa);var e=c.o;var f=d}lxa(this,c,d)}};
var Wxa={xH:!0};g.t(L3,J3);g.k=L3.prototype;g.k.AD=function(){g.Cn(this.fa)};
g.k.nN=function(){g.In(this.element,"ytp-rollup-mode");this.wk(this.Ea,!0)};
g.k.rz=function(){return this.A?this.N:this.I};
g.k.sz=function(){return this.A?this.I:this.N};
g.k.wk=function(a,b){this.Ea=a;if(this.u.params.u){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.za=this.N;this.I=this.N=0;J3.prototype.wk.call(this,a);qxa(this,b);J3.prototype.wk.call(this,a)}else J3.prototype.wk.call(this,a)};g.t(M3,g.ez);M3.prototype.toString=function(){return g.ez.prototype.toString.call(this)};g.t(N3,g.ez);N3.prototype.toString=function(){return g.ez.prototype.toString.call(this)};
var O3=0;g.t(P3,g.B);P3.prototype.A=function(){return[]};
P3.prototype.reset=function(){};g.t(Q3,P3);Q3.prototype.reset=function(){this.I={};this.u=this.o=null;this.G=!0};
Q3.prototype.A=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.p(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.p(e),c=e.next();!c.done;c=e.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var h=this.B,l={},m=c.getAttribute("p");m&&g.Ua(l,this.B[m]);m=S3(c,"b");null!=m&&
(l.bold=m);m=S3(c,"i");null!=m&&(l.Lf=m);m=S3(c,"u");null!=m&&(l.underline=m);m=T3(c,"et");null!=m&&(l.charEdgeStyle=m);m=T3(c,"of");null!=m&&(l.offset=m);m=V3(c,"bc");null!=m&&(l.background=m);m=V3(c,"ec");null!=m&&(l.vt=m);m=V3(c,"fc");null!=m&&(l.color=m);m=T3(c,"fs");null!=m&&0!==m&&(l.fontFamily=m);m=R3(c,"sz");void 0!==m&&(l.fontSizeIncrement=m/100-1);m=R3(c,"bo");void 0!==m&&(l.backgroundOpacity=m/255);m=R3(c,"fo");void 0!==m&&(l.textOpacity=m/255);m=T3(c,"rb");null!=m&&10!==m&&0!==m&&(l.oc=
10<m?m-1:m);c=T3(c,"hg");null!=c&&(l.Zz=c);h[d]=l;break;case "ws":d=c.getAttribute("id");this.N[d]=uxa(this,c);break;case "wp":d=c.getAttribute("id"),this.M[d]=vxa(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.p(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "w":this.o=wxa(this,d,e,!1);(d=this.I[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.I[this.o.id]=this.o;c.push(this.o);break;case "p":var n=e;h=[];l=d.getAttribute("w")||this.C;m=!!S3(d,
"a");n=(R3(d,"t")||0)+n;var q=R3(d,"d")||5E3;m||(!this.G&&this.u&&this.u.windowId===l&&this.u.end>n&&(this.u.end=n),this.u&&"\n"===this.u.text&&(this.u.text=""));var r=m?6:5,u=d.getAttribute("p");u=u?this.B[u]:null;var w=Array.from(d.childNodes);w.length&&(this.G=null!=d.getAttribute("d"));for(var z=0;z<w.length;z++){var A=w[z],D=void 0;0<z&&(m=!0);var F=void 0;1===A.nodeType&&(F=A);if(F&&"s"===F.tagName){if((A=(A=F.getAttribute("p"))?this.B[A]:null)&&A.oc&&(1===A.oc?(A=w.slice(z,z+4),4===A.length&&
(D=txa(n,q,l,m,r,A,this.B),z+=3)):D=txa(n,q,l,m,r,[F],this.B)),!D){var G=F;D=n;F=q;A=l;var S=m,aa=r,ec=G.textContent?G.textContent:"",Wc=G.getAttribute("p");Wc=Wc?this.B[Wc]:null;G=R3(G,"t")||0;D=new M3(D+G,F-G,aa,A,ec,S,Wc)}}else D=new M3(n,q,r,l,A.textContent||"",m,u);h.push(D);this.u=D}if(0<h.length)for(h[0].windowId===this.C&&(this.o=wxa(this,d,e,!0),c.push(this.o)),d=g.p(h),h=d.next();!h.done;h=d.next())h=h.value,h.windowId=this.o.id,this.o.o.push(h),c.push(h)}e=c}else e=[];return e};var Xxa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.t(W3,P3);W3.prototype.reset=function(){this.u.clear()};
W3.prototype.A=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens)for(var d=0,e=g.p(c.pens),f=e.next();!f.done;f=e.next()){f=f.value;var h={},l=f.pParentId;l&&Object.assign(h,this.o.get(l));f.bAttr&&(h.bold=!0);f.iAttr&&(h.Lf=!0);f.uAttr&&(h.underline=!0);l=f.ofOffset;null!=l&&(h.offset=l);void 0!==f.szPenSize&&(h.fontSizeIncrement=f.szPenSize/100-1);l=f.etEdgeType;null!=l&&(h.charEdgeStyle=l);void 0!==f.ecEdgeColor&&(h.vt=X3(f.ecEdgeColor));l=f.fsFontStyle;null!=l&&0!==l&&(h.fontFamily=l);
void 0!==f.fcForeColor&&(h.color=X3(f.fcForeColor));void 0!==f.foForeAlpha&&(h.textOpacity=f.foForeAlpha/255);void 0!==f.bcBackColor&&(h.background=X3(f.bcBackColor));void 0!==f.boBackAlpha&&(h.backgroundOpacity=f.boBackAlpha/255);(l=f.rbRuby)&&10!==l&&(h.oc=10<l?l-1:l,h.dg=Xxa.get(h.oc));f.hgHorizGroup&&(h.Zz=f.hgHorizGroup);this.o.set(d++,h)}if(c.wsWinStyles)for(d=0,e=g.p(c.wsWinStyles),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wsParentId)?Object.assign(h,this.C.get(l)):Object.assign(h,
this.F),void 0!==f.mhModeHint&&(h.vl=f.mhModeHint),void 0!==f.juJustifCode&&(h.textAlign=f.juJustifCode),void 0!==f.pdPrintDir&&(h.o=f.pdPrintDir),void 0!==f.sdScrollDir&&(h.A=f.sdScrollDir),void 0!==f.wfcWinFillColor&&(h.windowColor=X3(f.wfcWinFillColor)),void 0!==f.wfoWinFillAlpha&&(h.windowOpacity=f.wfoWinFillAlpha/255),this.C.set(d++,h);if(c.wpWinPositions)for(d=0,e=g.p(c.wpWinPositions),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wpParentId)&&Object.assign(h,this.B.get(l)),void 0!==f.ahHorPos&&
(h.Ne=f.ahHorPos),void 0!==f.apPoint&&(h.vf=f.apPoint),void 0!==f.avVerPos&&(h.gg=f.avVerPos),void 0!==f.ccCols&&(h.ai=f.ccCols),void 0!==f.rcRows&&(h.u=f.rcRows),this.B.set(d++,h);if(c.events)for(d=[],c=g.p(c.events),e=c.next();!e.done;e=c.next()){var m=e.value;e=(m.tStartMs||0)+b;f=m.dDurationMs||0;if(m.id)h=String(m.id),e=xxa(this,m,e,f,h),d.push(e),this.u.set(h,e);else{m.wWinId?h=m.wWinId.toString():(h="_"+O3++,l=xxa(this,m,e,f,h),d.push(l),this.u.set(h,l));0===f&&(f=5E3);l=this.u.get(h);var n=
!!m.aAppend,q=n?6:5,r=m.segs,u=null;m.pPenId&&(u=this.o.get(m.pPenId));for(m=0;m<r.length;m++){var w=r[m],z=w.utf8;if(z){var A=w.tOffsetMs||0,D=null;w.pPenId&&(D=this.o.get(w.pPenId));if(2===(null!=l.params.vl?l.params.vl:1<l.o.length?1:0)&&n&&"\n"===z)continue;if(w=D&&1===D.oc)if(w=m,w+3>=r.length||!r[w+1].pPenId||!r[w+2].pPenId||!r[w+3].pPenId)w=!1;else{var F=r[w+1].pPenId;(F=this.o.get(F))&&F.oc&&2===F.oc?(F=r[w+2].pPenId,F=this.o.get(F),!F||!F.oc||3>F.oc?w=!1:(F=r[w+3].pPenId,w=(F=this.o.get(F))&&
F.oc&&2===F.oc?!0:!1)):w=!1}if(w){A=r[m+1].utf8;w=r[m+3].utf8;F=r[m+2].utf8;var G=this.o.get(r[m+2].pPenId);z=sxa(z,A,F,w,G);n=new M3(e,f,q,h,z,n,D);m+=3}else n=new M3(e+A,f-A,q,l.id,z,n,D||u);n&&(d.push(n),l.o.push(n))}n=!0}}}else d=[];return d};Z3.prototype.clear=function(){this.A=this.time=this.mode=0;this.o=[];this.reset()};
Z3.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var yxa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];$3.prototype.set=function(a){this.type=a};
$3.prototype.get=function(){return this.type};
a4.prototype.clear=function(){this.state=0};
a4.prototype.update=function(){this.state=2===this.state?1:0};
a4.prototype.isValid=function(){return 0!==this.state};
a4.prototype.matches=function(a,b){return this.isValid()&&a===this.lj&&b===this.Xh};
Dxa.prototype.reset=function(){this.timestamp=this.o=0};
b4.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.A[b][c].timestamp=a};
b4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.A[b][c];a=0===d.o?a+"_":a+String.fromCharCode(d.o)}a+="\n"}return a};
b4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.A[b][c].reset();this.B=a;this.o=0;this.u=this.row=1};
var Exa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Fxa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Gxa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Hxa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];h4.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.u=this.F;this.B=this.G;this.o=this.u;var c=(a<<2)+(b<<1);this.F.reset(c);this.G.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
Y3.prototype.reset=function(a){this.C=a;this.o.clear();this.B=this.A;this.A.reset(a,0);this.F.reset(a,1)};Mxa.prototype.C=function(){};g.t(j4,Mxa);j4.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+O3++;c=c/1E3-this.G;d=d/1E3-this.G;a=new N3(c,d-c,5,f,{textAlign:0,vf:0,Ne:2.5*b,gg:5.33*a});e=new M3(c,d-c,5,f,e);this.A.push(a);this.A.push(e)}};
g.t(m4,P3);m4.prototype.A=function(a){a=new j4(a,a.byteLength,this.u);if(Nxa(a)){for(;a.o<a.u.byteLength;)for(0===a.version?a.B=l4(a)*(1E3/45):1===a.version&&(a.B=4294967296*l4(a)+l4(a)),a.F=k4(a);0<a.F;a.F--){var b=k4(a),c=k4(a),d=k4(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.o,b.o.push({time:a.B,type:this.track,vy:c,wy:d,order:b.o.length}))}Cxa(this.o,a);return a.A}return[]};
m4.prototype.reset=function(){this.o.clear()};g.t(o4,P3);
o4.prototype.A=function(a,b){for(var c=[],d=a.split(Yxa),e=1;e<d.length;e++){var f=d[e],h=b;if(""!==f&&!Zxa.test(f)){var l=C4.exec(f);if(l&&4<=l.length){var m=p4(l[1]),n=p4(l[2])-m;m+=h;var q=(l=l[3])?l.split(" "):[];l={};var r=null,u="",w=null,z="";l.textAlign=2;q=g.p(q);for(var A=q.next();!A.done;A=q.next())if(A=A.value.split(":"),2===A.length){var D=A[1];switch(A[0]){case "line":A=D.split(",");A[0].endsWith("%")&&(r=A[0],l.gg=Number.parseInt(r,10),2===A.length&&(u=A[1].trim()));break;case "position":A=
D.split(",");w=A[0];l.Ne=Number.parseInt(w,10);2===A.length&&(z=A[1].trim());break;case "align":switch(D){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}r||(l.gg=100,u||(u="end"));if(!w)switch(l.textAlign){case 0:l.Ne=0;break;case 1:l.Ne=100;break;default:l.Ne=50}r=0;switch(u){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(z){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.vf=0>r||8<r?7:r;f=f.substring(C4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");z=l;l=f;f={};if(0>l.indexOf("<")&&0>l.indexOf("&"))h=Pxa(m,n,5,z),n=new M3(m,n,5,h.id,l,!1,g.Ob(f)?void 0:f),c.push(h),c.push(n),h.o.push(n);else for(u=l.split($xa),1===u.length?(l=5,z=Pxa(m,n,l,z)):(r=l=6,z=Object.assign({ai:32},z),z=new N3(m,n,r,"_"+O3++,z)),c.push(z),r=m,w=0;w<u.length;w++)q=u[w],0===w%2?(A=g.z1("<html>"+q+"</html>"),A.getElementsByTagName("parsererror").length?
(D=A.createElement("span"),D.appendChild(A.createTextNode(q))):D=A.firstChild,Oxa(this,r,n-(r-m),l,z,0<w,D,f,c)):r=p4(q)+h}C4.lastIndex=0}}return c};
var Zxa=/^NOTE/,Yxa=/(?:\r\n|\r|\n){2,}/,C4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),$xa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.t(q4,g.B);q4.prototype.clear=function(){this.o&&this.o.dispose();this.o=null};
q4.prototype.reset=function(){this.o&&this.o.reset()};
q4.prototype.X=function(){g.B.prototype.X.call(this);this.clear()};var B4={windowColor:"#080808",windowOpacity:0,textAlign:2,vf:7,Ne:50,gg:100,Jb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.t(t4,g.RN);g.k=t4.prototype;g.k.X=function(){if(this.C||this.N){var a=this.H.app.C;a&&!a.ia()&&a.sm()}else Vxa(this,!1);g.RN.prototype.X.call(this)};
g.k.load=function(){var a=this;g.RN.prototype.load.call(this);var b=!g.P(this.A.experiments,"web_player_captions_track_list_changed_killswitch");this.G=this.player.getAudioTrack();if(this.u)this.o&&(this.fa.clear(),this.C?Sxa(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.yq(this.o,"json3",function(d,e,f,h){if(d){a.u.XC()&&(a.R=[],g.tQ(a.H.app,"captions",void 0),a.T.ib(),a.fa.reset());var l=a.fa;f=f||0;h=h||0;if(l.u.ha("html5_disable_rawcc_killswitch")){if("string"!==typeof d){var m=new DataView(d);
8<=m.byteLength&&1718909296===m.getUint32(4)&&(m=g.At(m,0,1835295092),d=d.slice(m.dataOffset,m.dataOffset+m.size),n4(d)||(d=g.hg(new Uint8Array(d))))}}else"string"===typeof d||n4(d)||(m=new DataView(d),d=8>=m.byteLength||1718909296!==m.getUint32(4)?"":(m=g.At(m,0,1835295092))&&m.size?g.hg(new Uint8Array(d.slice(m.dataOffset,m.dataOffset+m.size))):"");if(d)try{if("string"!==typeof d){var n=d,q=f,r=h;if(!n4(n))throw Error("Invalid binary caption track data");l.o||(l.o=new m4(r,e));var u=l.o.A(n,q)}else{if("WEBVTT"===
d.substring(0,6))e=d,r=f,l.o||(l.o=new o4),q=l.o.A(e,r),.01>Math.random()&&g.qr(Error("Deprecated subtitles format in web player: WebVTT")),n=q;else b:{q=d;if("{"===q[0])try{l.o||(l.o=new W3(Rxa(e)));n=l.o.A(q,f);break b}catch(G){g.pr(G);n=[];break b}r=g.z1(q);if(!r||!r.firstChild){var w=Error("Invalid caption track data");w.params=q;throw w;}if("timedtext"===r.firstChild.tagName){if(3===Number(r.firstChild.getAttribute("format"))){l.o||(l.o=new Q3(Rxa(e),l.u));n=l.o.A(r,f);break b}var z=Error("Unsupported subtitles format in web player (Format2)");
z.params=q;throw z;}if("transcript"===r.firstChild.tagName){var A=Error("Unsupported subtitles format in web player (Format1)");A.params=q;throw A;}var D=Error("Invalid caption track data");D.params=q;throw D;}u=n}var F=u}catch(G){g.pr(G),l.clear(),F=[]}else F=[];g.zN(a.player,F);!a.U||a.N||y4(a)||g.Gy(a.A)||g.Hy(a.A)||(a.aa.Ef(),F=rxa({vf:0,Ne:5,gg:5,u:2,textAlign:0,o:0,lang:"en"}),a.ba=[F],l=["Click "," for settings"],a.sa||(u=new g.cM(g.PM()),g.C(a,u),a.sa=u.element),u=F.end-F.start,(e=g.Zz(a.o))&&
a.ba.push(new M3(F.start,u,0,F.id,e)),a.ba.push(new M3(F.start,u,0,F.id,l[0]),new M3(F.start,u,0,F.id,a.sa,!0),new M3(F.start,u,0,F.id,l[1],!0)),g.zN(a.player,a.ba),a.aa.ib());!a.U||a.N||y4(a)||(z4(a,"module-enabled",!0),a.G&&(a.G.o=a.o),(F=g.V(a.player.app))&&g.YI(F.C));a.U=!1}}),!b||this.C||this.N||y4(this)||this.player.ra("captionschanged",A3(this.o))),b||(this.o&&!y4(this)?this.player.ra("captionschanged",A3(this.o)):this.player.ra("onCaptionsTrackListChanged"));
else{var c;this.oa?c=new H3(this.videoData.ka,this.player):this.za?c=new E3(this.A,this.videoData,this.player.getAudioTrack()):c=new I3(this.videoData.qm,this.videoData.videoId,this.videoData.captionsLanguagePreference||this.A.captionsLanguagePreference||g.PB(this.videoData,"yt:cc_default_lang")||this.A.ae,this.videoData.mt,this.A);this.u=c;g.C(this,this.u);c.zq(function(){var d;a.U||u4(a)?d=x4(a,a.U):v4(a)&&(d=w4(a));if(a.C||a.N){for(var e=a.u.Ej(!0),f=[],h=0;h<e.length;h++){var l=e[h],m=g.ve("TRACK");
m.setAttribute("kind","subtitles");m.setAttribute("label",g.Zz(l));m.setAttribute("srclang",B3(l));m.setAttribute("id",l.toString());a.N||m.setAttribute("src",a.u.Yk(l,"vtt"));l===d&&m.setAttribute("default","1");f.push(m)}d=a.H.app.C;d.lm(f);f=d.xa();a.ua&&a.Z.L(f.textTracks,"change",a.PN)}else!a.o&&d&&A4(a,d),a.player.ra("onCaptionsTrackListChanged"),a.player.ra("onApiChange")})}};
g.k.unload=function(){this.C&&this.o?Sxa(this,!1):(this.aa&&this.aa.Ef(),g.tQ(this.player.app,"captions",void 0),this.R=[],this.u&&this.u.Nh(),this.fa.clear(),this.I&&g.zN(this.player,this.I),this.ax());g.RN.prototype.unload.call(this);var a=g.V(this.player.app);a&&g.YI(a.C);this.player.ra("captionschanged",{})};
g.k.create=function(){(this.ga?this.C||this.N:v4(this)||u4(this))&&this.load()};
g.k.getTrackById=function(a){for(var b=this.u.Ej(!0),c=0;c<b.length;c++)if(b[c].toString()===a)return b[c];return null};
g.k.PN=function(){for(var a=this.H.app.C.xa().textTracks,b=null,c=0;c<a.length;c++)"showing"===a[c].mode&&(b=this.getTrackById(a[c].id));(this.loaded?this.o:null)!==b&&A4(this,b,!0)};
g.k.sP=function(){!this.o&&this.C||this.unload()};
g.k.kJ=function(a){this.R.push(a);this.T.ib()};
g.k.lJ=function(a){g.lb(this.R,a);this.u instanceof H3&&this.u.C&&g.zU(this.player.app,[a],void 0);this.T.ib()};
g.k.AO=function(a){if(a instanceof N3){var b=this.M[a.id];b&&b.u!==a&&(b.dispose(),delete this.M[a.id],b=null);b||(b=Txa(this,a))&&(this.M[a.id]=b)}else b=a.windowId,this.ea[b]||(this.ea[b]=[]),this.ea[b].push(a)};
g.k.GO=function(){Uxa(this,this.ba);this.ba=null};
g.k.lE=function(){var a=this;this.T.stop();g.Pb(this.ea);this.R.sort(g.gz);var b=this.R;if(this.I){var c=(0,g.Ce)(b,function(d){return-1===this.I.indexOf(d)},this);
c.length&&(b=c)}(0,g.y)(b,this.AO,this);g.Bb(this.M,function(d,e){a.ea[e]?(d.element.parentNode||(d instanceof L3||d instanceof K3||g.Eb(a.M,function(f,h){h!==e&&f.u.params.vf===d.u.params.vf&&f.u.params.Ne===d.u.params.Ne&&f.u.params.gg===d.u.params.gg&&(f.dispose(),delete a.M[h]);return h===e},a),g.DN(a.player,d.element,4)),d.wk(a.ea[e])):(d.dispose(),delete a.M[e])},this)};
g.k.MO=function(){r4(this,{},!0);g.P(this.A.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.ra("captionssettingschanged")};
g.k.SG=function(){var a=B4.Jb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Lf?3:a.bold?1:a.Lf?2:0,textOpacity:a.textOpacity,windowColor:B4.windowColor,windowOpacity:B4.windowOpacity};var b=s4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.tE=function(a,b){var c={};g.Ua(c,s4(this,"display-settings"));g.Ua(c,a);r4(this,c,b);this.player.ra("captionssettingschanged")};
g.k.ax=function(){!this.C&&this.loaded&&(g.Bb(this.M,function(a,b){a.dispose();delete this.M[b]},this),this.lE())};
g.k.cd=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Vd(b,-2,4);this.tE({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&A4(this,this.o,!0);break;case "stickyLoading":void 0!==b&&this.A.A&&z4(this,"module-enabled",!!b);break;case "track":if(!this.u)return{};if(b){if(this.C)break;if(!g.Qa(b))break;if(g.Ob(b)){A4(this,null,!0);break}for(var d=this.u.Ej(!0),e=0;e<d.length;e++){var f=d[e];f.languageCode!==b.languageCode||c&&f.languageName!==b.languageName||(c=b.translationLanguage?
Zwa(f,b.translationLanguage):f)}!c||c===this.o&&this.loaded||A4(this,c,!0)}else return this.loaded&&this.o&&!y4(this)?A3(this.o):{};return"";case "tracklist":return this.u?(0,g.Kc)(this.u.Ej(!(!b||!b.includeAsr)),function(h){return A3(h)}):[];
case "translationLanguages":return this.u?this.u.B.map(function(h){return Object.assign({},h)}):[];
case "sampleSubtitles":this.C||void 0===b||Vxa(this,!!b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.A.A&&a.push("stickyLoading");return a};
g.k.cI=function(){var a=this.o;return a?{cc:a.vssId}:{}};
g.k.nP=function(){this.loaded&&this.o&&!y4(this)?(z4(this,"module-enabled",!1),this.unload(),v4(this,!0)&&A4(this,w4(this),!1)):A4(this,y4(this)||!this.o?x4(this,!0):this.o,!0)};
g.k.dL=function(){var a=y4(this);v4(this,a)?A4(this,this.player.getAudioTrack().Ep,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),(this.ga?this.C||this.N:v4(this)||u4(this))&&(a?A4(this,x4(this),!1):this.load()))};g.bO.captions=t4;})(_yt_player);
